---
title: "Assignment 4"
author: "Anna Chamot"
date: "2025-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 4


```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(rtracklayer)
  library(epiwraps)
  library(GenomicRanges)
  library(R.utils) # unzip .gz archives
})

```

## Find and download from ENCODE the peaks (i.e. bed-like format) for the following in mouse embryonic stem cells (mESC) :

### Transcription factor p300
  
```{r}
dir.create("peaks")

download.file("https://www.encodeproject.org/files/ENCFF653YVR/@@download/ENCFF653YVR.bed.gz", "peaks/ep300.bed.gz") 
gunzip("peaks/ep300.bed.gz", remove=FALSE)

peaks_p300 <- rtracklayer::import("peaks/ep300.bed", format="narrowPeak")
head(peaks_p300)
``` 
### Histone modifications:
  * H3K4me3

```{r}
dir.create("peaks")

download.file("https://www.encodeproject.org/files/ENCFF974BMC/@@download/ENCFF974BMC.bed.gz", "peaks/H3K4me3.bed.gz") 
gunzip("peaks/H3K4me3.bed.gz", remove=FALSE)

peaks_H3K4me3 <- rtracklayer::import("peaks/H3K4me3.bed", format="narrowPeak")
head(peaks_H3K4me3)
``` 

  * H3K4me1

```{r}
dir.create("peaks")

download.file("https://www.encodeproject.org/files/ENCFF158GBZ/@@download/ENCFF158GBZ.bed.gz", "peaks/H3K4me1.bed.gz") 
gunzip("peaks/H3K4me1.bed.gz", remove=FALSE)

peaks_H3K4me1 <- rtracklayer::import("peaks/H3K4me1.bed", format="narrowPeak")
head(peaks_H3K4me1)
``` 

  * H3K27ac

```{r}
dir.create("peaks")

download.file("https://www.encodeproject.org/files/ENCFF519QMV/@@download/ENCFF519QMV.bed.gz", "peaks/H3K27ac.bed.gz") 
gunzip("peaks/H3K27ac.bed.gz", remove=FALSE)

peaks_H3K27ac <- rtracklayer::import("peaks/H3K27ac.bed", format="narrowPeak")
head(peaks_H3K27ac)
``` 
  
  * H3K27me3
  
```{r}
dir.create("peaks")

download.file("https://www.encodeproject.org/files/ENCFF008XKX/@@download/ENCFF008XKX.bed.gz", "peaks/H3K27me3.bed.gz") 
gunzip("peaks/H3K27me3.bed.gz", remove=FALSE)

peaks_H3K27me3 <- rtracklayer::import("peaks/H3K27me3.bed", format="narrowPeak")
head(peaks_H3K27me3)
``` 

## QUESTION: Of the p300 peaks, what proportion overlap each of the marks?

```{r}

ovelaps_p300_H3K4me1 <- findOverlaps(peaks_p300, peaks_H3K4me1, type = "any")
percentage_p300_H3K4me1 <- (length(ovelaps_p300_H3K4me1) / length(peaks_p300)) * 100

print(paste0(round(percentage_p300_H3K4me1, digits = 2), " % of p300 peaks overlap with H3K4me1 marks."))

ovelaps_p300_H3K4me3 <- findOverlaps(peaks_p300, peaks_H3K4me3, type = "any")
percentage_p300_H3K4me3 <- (length(ovelaps_p300_H3K4me3) / length(peaks_p300)) * 100

print(paste0(round(percentage_p300_H3K4me3, digits = 2), " % of p300 peaks overlap with H3K4me3 marks."))

ovelaps_p300_H3K27ac <- findOverlaps(peaks_p300, peaks_H3K27ac, type = "any")
percentage_p300_H3K27ac <- (length(ovelaps_p300_H3K27ac) / length(peaks_p300)) * 100

print(paste0(round(percentage_p300_H3K27ac, digits = 2), " % of p300 peaks overlap with H3K27ac marks."))

ovelaps_p300_H3K27me3 <- findOverlaps(peaks_p300, peaks_H3K27me3, type = "any")
percentage_p300_H3K27me3 <- (length(ovelaps_p300_H3K27me3) / length(peaks_p300)) * 100

print(paste0(round(percentage_p300_H3K27me3, digits = 2), " % of p300 peaks overlap with H3K27me3 marks."))
``` 



